In [2]:
import pylidc as pl
import numpy as np

In [3]:
# textureが1のアノテーションデータを取り出す
ann = pl.query(pl.Annotation).filter(pl.Annotation.texture == 1).all()

ann[0]

Annotation(id=88,scan_id=13)

In [4]:
ann_1 = pl.query(pl.Annotation.id).filter(pl.Annotation.texture == 1).all()

In [31]:
ann = pl.query(pl.Annotation).filter(pl.Annotation.texture == 1)[2]
contour = pl.query(pl.Contour).filter(pl.Contour.annotation_id == ann.id)
print ('ann:',ann)
print ('patient_id:', ann.scan.patient_id)
print ('ann.scan_id:',ann.scan_id)
print ('contour.count():', contour.count())
for i in range(len(contour.all())):
    print ('1:', contour[i])
    print ('2:', contour[i].annotation)
    print ('3:', contour[i].annotation.scan)
    print ('4:', contour[i].inclusion)
    print ('5:', contour[i].image_z_position)
    print ('6:', contour[i].dicom_file_name)
#     print (contour[i].coords)
    print (contour[i].image_k_position)
    print (contour[i].to_matrix())
    print ('--------------------------------------------------------------------')

ann: Annotation(id=123,scan_id=17)
patient_id: LIDC-IDRI-0006
ann.scan_id: 17
contour.count(): 4
1: Contour(id=568,annotation_id=123)
2: Annotation(id=123,scan_id=17)
3: Scan(id=17,patient_id=LIDC-IDRI-0006)
4: True
5: -151.5
6: 102.dcm
72
[[358 363  72]
 [359 362  72]
 [360 361  72]
 [361 360  72]
 [362 359  72]
 [363 359  72]
 [364 358  72]
 [364 357  72]
 [364 356  72]
 [363 356  72]
 [362 356  72]
 [361 356  72]
 [360 356  72]
 [359 356  72]
 [358 356  72]
 [357 356  72]
 [356 356  72]
 [356 357  72]
 [356 358  72]
 [356 359  72]
 [356 360  72]
 [356 361  72]
 [356 362  72]
 [356 363  72]
 [356 364  72]
 [356 365  72]
 [357 366  72]
 [357 367  72]
 [357 368  72]
 [358 368  72]
 [359 368  72]
 [359 367  72]
 [359 366  72]
 [359 365  72]
 [359 364  72]
 [358 363  72]]
--------------------------------------------------------------------
1: Contour(id=569,annotation_id=123)
2: Annotation(id=123,scan_id=17)
3: Scan(id=17,patient_id=LIDC-IDRI-0006)
4: True
5: -154.0
6: 41.dcm
71
[[362 37