In [44]:
import pylidc as pl
import numpy as np
import pydicom

In [3]:
target_dicom = '/Volumes/masashi/workspace/0_KML/0_medical/0_data/LIDC-IDRI/LIDC-IDRI-0002/01-01-2000-98329/3000522.000000-04919/1-063.dcm'

In [51]:
ann = pl.query(pl.Annotation).filter(pl.Annotation.texture == 1)[0]
mask = ann.boolean_mask()
vol = ann.scan.to_volume(False)
ann_mask = ann.scan

print (ann.id)
print (ann_mask)
print (ann_mask.patient_id)
# print (mask)
# print (mask.shape)
print (vol)
print (vol.shape)
print (ann_mask.slice_spacing)
print (ann_mask.slice_zvals)

88
Scan(id=13,patient_id=LIDC-IDRI-0002)
LIDC-IDRI-0002
[[[-3024 -3024 -3024 ... -3024 -3024 -3024]
  [-3024 -3024 -3024 ... -3024 -3024 -3024]
  [-3024 -3024 -3024 ... -3024 -3024 -3024]
  ...
  [-3024 -3024 -3024 ... -3024 -3024 -3024]
  [-3024 -3024 -3024 ... -3024 -3024 -3024]
  [-3024 -3024 -3024 ... -3024 -3024 -3024]]

 [[-3024 -3024 -3024 ... -3024 -3024 -3024]
  [-3024 -3024 -3024 ... -3024 -3024 -3024]
  [-3024 -3024 -3024 ... -3024 -3024 -3024]
  ...
  [-3024 -3024 -3024 ... -3024 -3024 -3024]
  [-3024 -3024 -3024 ... -3024 -3024 -3024]
  [-3024 -3024 -3024 ... -3024 -3024 -3024]]

 [[-3024 -3024 -3024 ... -3024 -3024 -3024]
  [-3024 -3024 -3024 ... -3024 -3024 -3024]
  [-3024 -3024 -3024 ... -3024 -3024 -3024]
  ...
  [-3024 -3024 -3024 ... -3024 -3024 -3024]
  [-3024 -3024 -3024 ... -3024 -3024 -3024]
  [-3024 -3024 -3024 ... -3024 -3024 -3024]]

 ...

 [[-3024 -3024 -3024 ... -3024 -3024 -3024]
  [-3024 -3024 -3024 ... -3024 -3024 -3024]
  [-3024 -3024 -3024 ... -3024 -30

In [65]:
contour = pl.query(pl.Contour).filter(pl.Contour.annotation_id == 88)

print (contour.all())
print (contour.count())
print (contour.first().to_matrix())

[Contour(id=390,annotation_id=88), Contour(id=391,annotation_id=88), Contour(id=392,annotation_id=88), Contour(id=393,annotation_id=88), Contour(id=394,annotation_id=88), Contour(id=395,annotation_id=88), Contour(id=396,annotation_id=88), Contour(id=397,annotation_id=88), Contour(id=398,annotation_id=88), Contour(id=399,annotation_id=88), Contour(id=400,annotation_id=88), Contour(id=401,annotation_id=88), Contour(id=402,annotation_id=88), Contour(id=403,annotation_id=88), Contour(id=404,annotation_id=88), Contour(id=405,annotation_id=88), Contour(id=406,annotation_id=88), Contour(id=407,annotation_id=88), Contour(id=408,annotation_id=88), Contour(id=409,annotation_id=88), Contour(id=410,annotation_id=88), Contour(id=411,annotation_id=88), Contour(id=412,annotation_id=88), Contour(id=413,annotation_id=88), Contour(id=414,annotation_id=88), Contour(id=415,annotation_id=88), Contour(id=416,annotation_id=88), Contour(id=417,annotation_id=88), Contour(id=418,annotation_id=88), Contour(id=41

In [22]:
contour.annotation_id

AttributeError: 'Query' object has no attribute 'annotation_id'

In [62]:
ds = pydicom.dcmread(target_dicom)

print (ds.pixel_array)
print (ds.pixel_array.shape)

[[-2000 -2000 -2000 ... -2000 -2000 -2000]
 [-2000 -2000 -2000 ... -2000 -2000 -2000]
 [-2000 -2000 -2000 ... -2000 -2000 -2000]
 ...
 [-2000 -2000 -2000 ... -2000 -2000 -2000]
 [-2000 -2000 -2000 ... -2000 -2000 -2000]
 [-2000 -2000 -2000 ... -2000 -2000 -2000]]
(512, 512)
